name: Docker Image CI

on:
  push:
    branches: [ vaccel-0.23, vaccel-0.23-extend, vaccel-main ]
    paths:
      - '**/Dockerfile*'
      - 'tools/devtool'
      - '.github/workflows/create_image.yml'
  pull_request:
    branches: [ vaccel-0.23 vaccel-main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, "${{ matrix.arch }}" ]
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false

    steps:
    - uses: actions/checkout@main

    - name: Build docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nubificus/fcuvm
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "${{matrix.arch}}-main"
        dockerfile: "${{github.workspace}}/tools/devctr/Dockerfile.${{matrix.arch}}"

  manifest:
    runs-on: [ self-hosted, aarch64 ]
    needs: build
    steps:
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Manifest images under one label
        shell: bash {0}
        run: |
          docker manifest rm nubificus/fcuvm:vaccel-main
          docker manifest create nubificus/fcuvm:vaccel-main \
            --amend nubificus/fcuvm:x86_64-main \
            --amend nubificus/fcuvm:aarch64-main
          docker manifest push nubificus/fcuvm:vaccel-main
