name: Docker Image CI

on:
  push:
    branches: [ vaccel-0.23, vaccel-0.23-extend ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, "${{ matrix.arch }}" ]
    strategy:
      matrix: 
        arch: [X64, aarch64]
      fail-fast: false

    steps:
    - uses: actions/checkout@main

    - name: Set Dockerfile name & Tags
      id: set-dockerfile-name
      run: |
        if [[ "${{ matrix.arch }}" == "X64" ]]
        then
          Dockerfile="${{github.workspace}}/tools/devctr/Dockerfile.x86_64"
          tag="x86_64"
          echo "::set-output name=dfile::$Dockerfile"
          echo "::set-output name=atag::$tag"
        else
          Dockerfile="${{github.workspace}}/tools/devctr/Dockerfile.aarch64"
          tag="arm64"
          echo "::set-output name=dfile::$Dockerfile"
          echo "::set-output name=atag::$tag"
        fi

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name:  nubificus/fcuvm
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "${{ steps.set-dockerfile-name.outputs.atag }}"
        dockerfile: ${{ steps.set-dockerfile-name.outputs.dfile }}
